baseURL = "https://demo.webwork.rochester.edu"
languageCode = "en-us"
title = "WeBWorK Online Math Homework Demo Site"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 8 # is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "images/favicon.ico"
  description = "Ask the questions you should not just the questions you can"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/openwebwork"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-green"
  featured_image = ""
  recent_posts_number = 2
  mainSections = ["ww_course"]
