---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/info
  label: Info
  create: all
  match: "**/*"
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
- type: directory
  path: content/language
  label: Language
  create: all
  match: "**/*"
- type: directory
  path: content/hands-on
  label: Hands on
  create: all
  match: "**/*"
- type: directory
  path: content/features
  label: Features
  create: all
  match: "**/*"
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: content/labs
  label: Labs
  create: all
  match: "**/*"
- type: directory
  path: content/courses
  label: Courses
  create: all
  match: "**/*"
- type: directory
  path: content/tutorials
  label: Tutorials
  create: all
  match: "**/*"
- type: directory
  path: content/TheWebworkProject
  label: Thewebworkproject
  create: all
  match: "**/*"
- type: directory
  path: content/ww_moodle
  label: Ww moodle
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
version: 0.55.6
